import assert from 'node:assert/strict';
import { test } from 'node:test';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, mkdir, symlink, readlink, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
const exec = promisify(execFile);
test('candidate installation is independent of cwd and preserves the current release until explicit activation', async t => {
  const root=await mkdtemp(join(tmpdir(),'roost-workbench-release-'));
  t.after(()=>rm(root,{recursive:true,force:true}));
  const repo=fileURLToPath(new URL('../../',import.meta.url));
  await exec(process.execPath,[join(repo,'stable-workbench/build.mjs')],{cwd:root});
  const install=join(root,'installed'); await mkdir(join(install,'releases','old'),{recursive:true});
  await symlink('releases/old',join(install,'current'));
  const script=join(repo,'scripts/install-workbench.mjs'),env={...process.env,WORKBENCH_INSTALL_DIR:install,NODE_PATH:'',NODE_OPTIONS:''};
  await exec(process.execPath,[script],{cwd:root,env});
  assert.equal(await readlink(join(install,'current')),'releases/old');
  const manifest=JSON.parse(await readFile(join(repo,'stable-workbench/dist/manifest.json'),'utf8'));
  const target=`releases/${manifest.version}-${manifest.buildId}`;
  const entry=join(install,target,'server.mjs');
  const checked=JSON.parse((await exec(process.execPath,[entry,'--check'],{cwd:root,env})).stdout);
  assert.equal(checked.buildId,manifest.buildId);
  await exec(process.execPath,[script,'--activate'],{cwd:root,env});
  assert.equal(await readlink(join(install,'previous')),'releases/old'); assert.equal(await readlink(join(install,'current')),target);
  const before=await readFile(entry);await exec(process.execPath,[script],{cwd:root,env});assert.deepEqual(await readFile(entry),before);
  assert.equal(manifest.inputs.some((p:string)=>/frontend\/src\/app\/App.tsx$/.test(p)),true);
  assert.equal(manifest.inputs.some((p:string)=>/backend\/src|https?:/.test(p)),false);
});
